version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: shepherd_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - shepherd_network

  # Supabase Local Development Stack
  supabase:
    image: supabase/supabase:latest
    container_name: shepherd_supabase
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "54321:8000"  # API Gateway
      - "54322:8080"  # Database REST API
      - "54323:3000"  # Auth
      - "54324:5000"  # Storage
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE5NTczNDkyMDB9.VJHvXuXgMVUfEjGD7J5sJsj_ZXJiYXSgvgPDrxGvZqQ
      SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJpYXQiOjE2NDE3NjkyMDAsImV4cCI6MTk1NzM0OTIwMH0.5jN7vJ8WGZmQoSfZRLgYzPJXWkNMIEJpOzYwZPn0DWY
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE5NTczNDkyMDB9.VJHvXuXgMVUfEjGD7J5sJsj_ZXJiYXSgvgPDrxGvZqQ
    volumes:
      - ./supabase:/app/supabase
    networks:
      - shepherd_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: shepherd_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shepherd_network

volumes:
  postgres_data:
  redis_data:

networks:
  shepherd_network:
    driver: bridge